
package ru.iokhin.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-03T10:44:36.899+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "AuthException", targetNamespace = "http://endpoint.tm.iokhin.ru/")
public class AuthException_Exception extends Exception {

    private ru.iokhin.tm.endpoint.AuthException authException;

    public AuthException_Exception() {
        super();
    }

    public AuthException_Exception(String message) {
        super(message);
    }

    public AuthException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthException_Exception(String message, ru.iokhin.tm.endpoint.AuthException authException) {
        super(message);
        this.authException = authException;
    }

    public AuthException_Exception(String message, ru.iokhin.tm.endpoint.AuthException authException, java.lang.Throwable cause) {
        super(message, cause);
        this.authException = authException;
    }

    public ru.iokhin.tm.endpoint.AuthException getFaultInfo() {
        return this.authException;
    }
}
