
package ru.iokhin.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-31T11:32:36.576+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "ClassNotFoundException", targetNamespace = "http://endpoint.tm.iokhin.ru/")
public class ClassNotFoundException_Exception extends Exception {

    private ru.iokhin.tm.endpoint.ClassNotFoundException classNotFoundException;

    public ClassNotFoundException_Exception() {
        super();
    }

    public ClassNotFoundException_Exception(String message) {
        super(message);
    }

    public ClassNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClassNotFoundException_Exception(String message, ru.iokhin.tm.endpoint.ClassNotFoundException classNotFoundException) {
        super(message);
        this.classNotFoundException = classNotFoundException;
    }

    public ClassNotFoundException_Exception(String message, ru.iokhin.tm.endpoint.ClassNotFoundException classNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.classNotFoundException = classNotFoundException;
    }

    public ru.iokhin.tm.endpoint.ClassNotFoundException getFaultInfo() {
        return this.classNotFoundException;
    }
}
