package ru.iokhin.tm.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-03T10:44:36.435+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "ProjectEndpointBeanService",
                  wsdlLocation = "http://localhost:8080/ProjectEndpointBean?wsdl",
                  targetNamespace = "http://endpoint.tm.iokhin.ru/")
public class ProjectEndpointBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.tm.iokhin.ru/", "ProjectEndpointBeanService");
    public final static QName ProjectEndpointBeanPort = new QName("http://endpoint.tm.iokhin.ru/", "ProjectEndpointBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ProjectEndpointBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProjectEndpointBeanService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ProjectEndpointBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProjectEndpointBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProjectEndpointBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectEndpointBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProjectEndpointBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProjectEndpointBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProjectEndpointBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProjectEndpointBean
     */
    @WebEndpoint(name = "ProjectEndpointBeanPort")
    public ProjectEndpointBean getProjectEndpointBeanPort() {
        return super.getPort(ProjectEndpointBeanPort, ProjectEndpointBean.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectEndpointBean
     */
    @WebEndpoint(name = "ProjectEndpointBeanPort")
    public ProjectEndpointBean getProjectEndpointBeanPort(WebServiceFeature... features) {
        return super.getPort(ProjectEndpointBeanPort, ProjectEndpointBean.class, features);
    }

}
