package ru.iokhin.tm.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-18T17:13:04.652+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "ServerInfoEndpointService",
                  wsdlLocation = "http://127.0.0.1:80/ServerInfoEndpointBean?wsdl",
                  targetNamespace = "http://endpoint.tm.iokhin.ru/")
public class ServerInfoEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.tm.iokhin.ru/", "ServerInfoEndpointService");
    public final static QName ServerInfoEndpointPort = new QName("http://endpoint.tm.iokhin.ru/", "ServerInfoEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:80/ServerInfoEndpointBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServerInfoEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:80/ServerInfoEndpointBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServerInfoEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServerInfoEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerInfoEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServerInfoEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServerInfoEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServerInfoEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServerInfoEndpoint
     */
    @WebEndpoint(name = "ServerInfoEndpointPort")
    public ServerInfoEndpoint getServerInfoEndpointPort() {
        return super.getPort(ServerInfoEndpointPort, ServerInfoEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerInfoEndpoint
     */
    @WebEndpoint(name = "ServerInfoEndpointPort")
    public ServerInfoEndpoint getServerInfoEndpointPort(WebServiceFeature... features) {
        return super.getPort(ServerInfoEndpointPort, ServerInfoEndpoint.class, features);
    }

}
