package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-18T17:13:04.649+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "ServerInfoEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerInfoEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/ServerInfoEndpoint/getServerInfoRequest", output = "http://endpoint.tm.iokhin.ru/ServerInfoEndpoint/getServerInfoResponse")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetServerInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.ServerInfo getServerInfo();
}
