package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-18T17:16:51.408+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "SessionEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface SessionEndpointBean {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/createRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.SessionDTO create(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/removeRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/removeResponse")
    @RequestWrapper(localName = "remove", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveResponse")
    public void remove(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/validateRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/validateResponse")
    @RequestWrapper(localName = "validate", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.ValidateResponse")
    public void validate(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.SessionDTO session
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/findByIdRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/findByIdResponse")
    @RequestWrapper(localName = "findById", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.SessionDTO findById(
        @WebParam(name = "session", targetNamespace = "")
        java.lang.String session
    );
}
