
package ru.iokhin.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-30T17:42:12.738+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "SOAPException", targetNamespace = "http://endpoint.tm.iokhin.ru/")
public class SOAPException_Exception extends Exception {

    private ru.iokhin.tm.endpoint.SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }

    public SOAPException_Exception(String message) {
        super(message);
    }

    public SOAPException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, ru.iokhin.tm.endpoint.SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, ru.iokhin.tm.endpoint.SOAPException soapException, java.lang.Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public ru.iokhin.tm.endpoint.SOAPException getFaultInfo() {
        return this.soapException;
    }
}
