package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-31T11:32:36.339+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "TaskEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpointBean {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/remove/Fault/AuthException")})
    @RequestWrapper(localName = "remove", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Project remove(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/addTaskRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/addTaskResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/addTask/Fault/AuthException")})
    @RequestWrapper(localName = "addTask", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddTask")
    @ResponseWrapper(localName = "addTaskResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Task addTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findByPartOfNameOrDescriptionTaskRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findByPartOfNameOrDescriptionTaskResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findByPartOfNameOrDescriptionTask/Fault/AuthException")})
    @RequestWrapper(localName = "findByPartOfNameOrDescriptionTask", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByPartOfNameOrDescriptionTask")
    @ResponseWrapper(localName = "findByPartOfNameOrDescriptionTaskResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByPartOfNameOrDescriptionTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.iokhin.tm.endpoint.Task> findByPartOfNameOrDescriptionTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "keyWord", targetNamespace = "")
        java.lang.String keyWord
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByProjectIdRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByProjectIdResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByProjectId/Fault/AuthException")})
    @RequestWrapper(localName = "removeAllByProjectId", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveAllByProjectId")
    @ResponseWrapper(localName = "removeAllByProjectIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveAllByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeAllByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/sortTaskByUserIdRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/sortTaskByUserIdResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/sortTaskByUserId/Fault/AuthException")})
    @RequestWrapper(localName = "sortTaskByUserId", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.SortTaskByUserId")
    @ResponseWrapper(localName = "sortTaskByUserIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.SortTaskByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.iokhin.tm.endpoint.Task> sortTaskByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "comparator", targetNamespace = "")
        java.lang.String comparator
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByUserIdRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByUserIdResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/removeAllByUserId/Fault/AuthException")})
    @RequestWrapper(localName = "removeAllByUserId", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveAllByUserId")
    @ResponseWrapper(localName = "removeAllByUserIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.RemoveAllByUserIdResponse")
    public void removeAllByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByUserIdRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByUserIdResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByUserId/Fault/AuthException")})
    @RequestWrapper(localName = "findAllByUserId", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindAllByUserId")
    @ResponseWrapper(localName = "findAllByUserIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindAllByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.iokhin.tm.endpoint.Project> findAllByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByProjectIdRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByProjectIdResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/findAllByProjectId/Fault/AuthException")})
    @RequestWrapper(localName = "findAllByProjectId", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindAllByProjectId")
    @ResponseWrapper(localName = "findAllByProjectIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindAllByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.iokhin.tm.endpoint.Task> findAllByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/editRequest", output = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/editResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/TaskEndpointBean/edit/Fault/AuthException")})
    @RequestWrapper(localName = "edit", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.EditResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Project edit(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "status", targetNamespace = "")
        ru.iokhin.tm.endpoint.Status status
    ) throws AuthException_Exception;
}
