package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-31T11:32:36.591+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "UserEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpointBean {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONLoadRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONLoad/Fault/IOException")})
    @RequestWrapper(localName = "dataFasterJSONLoad", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterJSONLoad")
    @ResponseWrapper(localName = "dataFasterJSONLoadResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterJSONLoadResponse")
    public void dataFasterJSONLoad() throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinLoadRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinLoad/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinLoad/Fault/ClassNotFoundException")})
    @RequestWrapper(localName = "dataBinLoad", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataBinLoad")
    @ResponseWrapper(localName = "dataBinLoadResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataBinLoadResponse")
    public void dataBinLoad() throws IOException_Exception, ClassNotFoundException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONSaveRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONSave/Fault/JAXBException")})
    @RequestWrapper(localName = "dataJAXBJSONSave", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBJSONSave")
    @ResponseWrapper(localName = "dataJAXBJSONSaveResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBJSONSaveResponse")
    public void dataJAXBJSONSave() throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/passChangeRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/passChangeResponse")
    @RequestWrapper(localName = "passChange", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.PassChange")
    @ResponseWrapper(localName = "passChangeResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.PassChangeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean passChange(
        @WebParam(name = "oldPassword", targetNamespace = "")
        java.lang.String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        java.lang.String newPassword
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONLoadRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBJSONLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "dataJAXBJSONLoad", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBJSONLoad")
    @ResponseWrapper(localName = "dataJAXBJSONLoadResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBJSONLoadResponse")
    public void dataJAXBJSONLoad() throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByIdRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByIdResponse")
    @RequestWrapper(localName = "findById", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User findById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLLoadRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLLoad/Fault/IOException")})
    @RequestWrapper(localName = "dataFasterXMLLoad", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterXMLLoad")
    @ResponseWrapper(localName = "dataFasterXMLLoadResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterXMLLoadResponse")
    public void dataFasterXMLLoad() throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLSaveRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLSave/Fault/JAXBException")})
    @RequestWrapper(localName = "dataJAXBXMLSave", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBXMLSave")
    @ResponseWrapper(localName = "dataJAXBXMLSaveResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBXMLSaveResponse")
    public void dataJAXBXMLSave() throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUserResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUser/Fault/AuthException")})
    @RequestWrapper(localName = "editUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.EditUser")
    @ResponseWrapper(localName = "editUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.EditUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User editUser(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "newLogin", targetNamespace = "")
        java.lang.String newLogin,
        @WebParam(name = "newPasswordHash", targetNamespace = "")
        java.lang.String newPasswordHash
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUserResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUser/Fault/AuthException")})
    @RequestWrapper(localName = "authUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AuthUser")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AuthUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Session authUser(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByLoginRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByLoginResponse")
    @RequestWrapper(localName = "findByLogin", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByLogin")
    @ResponseWrapper(localName = "findByLoginResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User findByLogin(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLLoadRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataJAXBXMLLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "dataJAXBXMLLoad", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBXMLLoad")
    @ResponseWrapper(localName = "dataJAXBXMLLoadResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataJAXBXMLLoadResponse")
    public void dataJAXBXMLLoad() throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/getCurrentUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User getCurrentUser();

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLSaveRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLSaveResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterXMLSave/Fault/IOException")})
    @RequestWrapper(localName = "dataFasterXMLSave", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterXMLSave")
    @ResponseWrapper(localName = "dataFasterXMLSaveResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterXMLSaveResponse")
    public void dataFasterXMLSave() throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinSaveRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinSaveResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataBinSave/Fault/IOException")})
    @RequestWrapper(localName = "dataBinSave", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataBinSave")
    @ResponseWrapper(localName = "dataBinSaveResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataBinSaveResponse")
    public void dataBinSave() throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONSaveRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONSaveResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/dataFasterJSONSave/Fault/IOException")})
    @RequestWrapper(localName = "dataFasterJSONSave", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterJSONSave")
    @ResponseWrapper(localName = "dataFasterJSONSaveResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.DataFasterJSONSaveResponse")
    public void dataFasterJSONSave() throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/addUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/addUserResponse")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User addUser(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
