package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-30T19:01:10.394+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "UserEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpointBean {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUserResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/editUser/Fault/AuthException")})
    @RequestWrapper(localName = "editUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.EditUser")
    @ResponseWrapper(localName = "editUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.EditUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User editUser(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session,
        @WebParam(name = "newLogin", targetNamespace = "")
        java.lang.String newLogin,
        @WebParam(name = "newPasswordHash", targetNamespace = "")
        java.lang.String newPasswordHash
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/passChangeRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/passChangeResponse")
    @RequestWrapper(localName = "passChange", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.PassChange")
    @ResponseWrapper(localName = "passChangeResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.PassChangeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean passChange(
        @WebParam(name = "oldPassword", targetNamespace = "")
        java.lang.String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        java.lang.String newPassword
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUserResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/UserEndpointBean/authUser/Fault/AuthException")})
    @RequestWrapper(localName = "authUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AuthUser")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AuthUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Session authUser(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws AuthException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByLoginRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByLoginResponse")
    @RequestWrapper(localName = "findByLogin", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByLogin")
    @ResponseWrapper(localName = "findByLoginResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User findByLogin(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/getCurrentUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User getCurrentUser();

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/addUserRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/addUserResponse")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User addUser(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByIdRequest", output = "http://endpoint.tm.iokhin.ru/UserEndpointBean/findByIdResponse")
    @RequestWrapper(localName = "findById", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.User findById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
